### ISSUE TITLE
ansible 004 - create jenkins.yml

### ISSUE THREAD

**Issue by mhristof** [mhristof/solid-telegram#22]
Create top level jenkins.yml that installs the Jenkins role

```yaml
- hosts: all
  roles:
    - jenkins
```
